config/routes.rb
OutputerLinestudyApp::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :linestudies

  root  'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'

  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  
  

  

end

app/models/linestudy.rb
class Linestudy < ActiveRecord::Base
	belongs_to :user
	has_many :events, dependent: :destroy

	default_scope -> { order('created_at DESC') }

	validates :name, presence: true, length: { maximum: 80 }
	validates :description, length: { maximum: 200 }
	validates :category, length: { maximum: 80 }
	validates :user_id, presence: true, numericality: {only_integer: true}
	validates :start_time, presence: true
	
	validates_datetime :start_time, :after => lambda { 5.years.ago },
			:after_message => "must be within 5 years", 
			:before => lambda { 1.minute.ago },
			:before_message => "cannot be in the future" 
	# validates_datetime :end_time, :after => lambda { 5.years.ago },
	# 		:after_message => "must be within 5 years", 
	# 		:before => lambda { 1.minute.ago },
	# 		:before_message => "cannot be in the future"
end

app/controllers/linestudies_controller.rb
class LinestudiesController < ApplicationController
  before_action :signed_in_user, only: [:create, :show, :edit, :update, :destroy]

  # GET /linestudies
  # GET /linestudies.json
  def index
    @linestudies = current_user.linestudies.all
  end

  # GET /linestudies/1
  # GET /linestudies/1.json
  def show
    @user = current_user
    @linestudy = @user.linestudies.find(params[:id])
    @events = @linestudy.events.all
  end

  # GET /linestudies/new
  def new
  end

  # GET /linestudies/1/edit
  def edit
  end

  # POST /linestudies
  # POST /linestudies.json
  def create
    @linestudy = current_user.linestudies.build(linestudy_params)
    if @linestudy.save
      flash[:success] = "Linestudy created!"
      redirect_to root_url
    else
      render 'static_pages/home'
    end
  end

  # PATCH/PUT /linestudies/1
  # PATCH/PUT /linestudies/1.json
  def update
    respond_to do |format|
      if @linestudy.update(linestudy_params)
        format.html { redirect_to @linestudy, notice: 'Linestudy was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @linestudy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /linestudies/1
  # DELETE /linestudies/1.json
  def destroy
    @linestudy.destroy
    respond_to do |format|
      format.html { redirect_to linestudies_url }
      format.json { head :no_content }
    end
  end

  def save
    @linestudy = current_user.linestudies.find_by_id(params[:id])
    @events = @linestudy.events

    Rails.logger.info("We have entered linestudies Save (in linestudies Controller)")
    Rails.logger.info("The linestudy description is " + @linestudy.description.to_yaml)
    Rails.logger.info("The CURRENT events are " + @events.to_yaml)
    Rails.logger.info("js_events are " + params[:line_study_table].to_yaml)
    # create function to sync js table with rails table
    respond_to do |format|
      format.html {redirect_to 'show'}
      format.js do
        js_events = params[:line_study_table]
        Rails.logger.info("When saving, the current js_events are " + js_events.to_yaml)
        update_events(@events, js_events, @linestudy)
        delete_events(@events, js_events)
        render nothing: true
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_linestudy
      @linestudy = Linestudy.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def linestudy_params
      params.require(:linestudy).permit(:name, :description, :category, :start_time, :end_time)
    end

    def update_events(events, js_events, study)
      #update and create rails events based on the js events

      Rails.logger.info('We have entered update_events (in linestudiesController')
      Rails.logger.info("Within update_events, the current events are " + events.to_yaml)
      Rails.logger.info("Within update_events, the current js_events are " + js_events.to_yaml)
      Rails.logger.info("within update_events, the study is " + study.to_yaml)

      js_events.each do |js_event|
        Rails.logger.info("
        javascript event (js_event):  " + js_event.to_s() + "
        ")
        js_event_items = js_event[1]   #because each js_event is an array with 1 element
        Rails.logger.info("Its js_id is " + js_event_items['js_id'].to_s)

        if js_event_items["js_id"] == ""
          Rails.logger.info("It's a new event!!!")
          new_event = study.events.build(js_id: study.events.max_by {|e| e.js_id}.js_id+ 1, start_time: js_event_items["start_time"], 
                                          stop_time: js_event_items["stop_time"], description: js_event_items["description"] , 
                                          status: js_event_items["status"] , speed: js_event_items["speed"],
                                          machine_id: study.machine_id, line_id: study.line_id)
          Rails.logger.info('Event created')
          new_event.save!
        else
          event_js_id = js_event_items["js_id"].to_i
          if (events.exists?(js_id: event_js_id)) && (js_event_items["js_id"] != "")
            existing_event = events.where(js_id: event_js_id)[0]
            existing_event.update_attributes(start_time: js_event_items["start_time"], stop_time: js_event_items["stop_time"],
                    description: js_event_items["description"], status: js_event_items["status"], speed: js_event_items["speed"])
            Rails.logger.info('                       Event updated')
            existing_event.save!
          else
            raise("Something funky is happening- a new event came in with a js_id that is not null nor existing.")
          end
        end
      end
  end


  def delete_events(events, js_events)
    #delete any rails objects that no longer exist in the js
    Rails.logger.info('We have entered delete_events (in lineStudiesController')
    e_ids = Array.new
    js_events.each do |js_e|      
      js_event = js_e[1]
      e_ids.push(js_event["js_id"].to_i)
    end
    events.each do |eve|
      Rails.logger.info("E_IDS  " + e_ids.to_s + " ; EVENT JS ID  " + eve.js_id.to_s + "\n")
      if not e_ids.include?(eve.js_id)
        Rails.logger.info("We are deleting an event!")
        eve.destroy
      end
    end
  end

end

app/helpers/linestudies_helper.rb
module LinestudiesHelper
end

app/views/linestudies/_form.html.erb
<%= form_for(@linestudy) do |f| %>
  <% if @linestudy.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@linestudy.errors.count, "error") %> prohibited this linestudy from being saved:</h2>

      <ul>
      <% @linestudy.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :start_time %><br>
    <%= f.datetime_select :start_time %>
  </div>
  <div class="field">
    <%= f.label :end_time %><br>
    <%= f.datetime_select :end_time %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/linestudies/_linestudy.html.erb
<li>
  <span class="name"><%= link_to linestudy.name, linestudy %></span>
  <span class="description"><%= linestudy.description %></span>
  <span class="timestamp">
    Created <%= time_ago_in_words(linestudy.created_at) %> ago.
  </span>
</li>

app/views/linestudies/edit.html.erb
<h1>Editing linestudy</h1>

<%= render 'form' %>

<%= link_to 'Show', @linestudy %> |
<%= link_to 'Back', linestudies_path %>

app/views/linestudies/index.html.erb
<h1>Listing linestudies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Category</th>
      <th>User</th>
      <th>Start time</th>
      <th>End time</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @linestudies.each do |linestudy| %>
      <tr>
        <td><%= linestudy.name %></td>
        <td><%= linestudy.description %></td>
        <td><%= linestudy.category %></td>
        <td><%= linestudy.user_id %></td>
        <td><%= linestudy.start_time %></td>
        <td><%= linestudy.end_time %></td>
        <td><%= link_to 'Show', linestudy %></td>
        <td><%= link_to 'Edit', edit_linestudy_path(linestudy) %></td>
        <td><%= link_to 'Destroy', linestudy, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Linestudy', new_linestudy_path %>

app/views/linestudies/new.html.erb
<h1>New linestudy</h1>

<%= render 'form' %>

<%= link_to 'Back', linestudies_path %>

app/views/linestudies/show.html.erb
<% provide(:title, 'Linestudy') %>
<div id="page-content" class="row">
  <div class="col-md-12 well">
    
    <div class="float-left">
      <p><%= @linestudy.description %></p>
    </div>
  </div>
  <div class="col-md-12 well">
    <%= link_to 'Back', '#',:id => 'back_to_results', :class =>"btn btn-warning" %>
    <br><br>
    <div class="table-responsive">
      <table id='line-study-table' class="table table-bordered table-hover table-condensed">
        <thead>
          <tr>
            <th class='col_id' style='display:none;'>ID</i></th>
            <th class='col_icon'><i class="glyphicon-plus"></i></th>
            <th class='col_sta'>Start</th>
            <th class='col_end'>End</th>
            <th class='col_dur'>Duration (minutes)</th>
            <th class='col_des'>Description</th>
            <th class='col_mac'>Machine Status</th>
            <th class='col_spe'>Speed</th>
            <th class='col_icon'></th>
          </tr>
        </thead>
        <tbody>

          <% iter = 0 %> 
          <% @events.each do |event| %>
            <tr>
              <td class='row_id' style='display:none;'><%= iter %></td>
              <td><i class='glyphicon-plus'></i></td>
              <td class='ls_row col_sta'><%= event.event_start.strftime "%H:%M:%S" %></td>
              <td class='ls_row col_end'><%= event.event_stop.strftime "%H:%M:%S" %></td>
              <td class='ls_row col_dur'><%= ((event.duration)) %></td>
              <td class='ls_row col_des'><%= event.event_description %></td>
              <td class='ls_row col_mac'><%= event.status %></td>
              <td class='ls_row col_spe'><%= event.speed %></td>
              <td><i class='glyphicon-minus'></i></td>
            </tr>
            <% iter = iter + 1 %>
          <% end %>


        </tbody>
      </table>
    </div>

    <%= link_to 'Submit', '#', :id => "save_linestudy_link", :class =>"btn btn-warning",:ajax_path => linestudy_path %>
  </div>
</div>